### ISSUE TITLE
is build.manifest missing ? 

### ISSUE THREAD

**Issue by ldgeo** [3liz/py-qgis-server#12]
Hi, 

i ran into a first exception when i tried to install py-qgis-server and ran it for the first time (in dev mode): 

```
Failed to read manifest !: [Errno 2] No such file or directory: '/home/.../py-qgis-server/pyqgisserver/build.manifest' 
qgisserver n/a (build n/a,commit n/a)
``` 

What is the purpose of this manifest file ? Is it missing from the repository or we should generate it with `make manifest`? 
If so It should be documented :wink:

**Comment by dmarteau** [comment]
The manifest is generated vwith `make manifiest` or `make dist`, it is stored with the package source for displaying version info at startup. 

This only a warning, the lack of manifest do not prevent the package from running correctly.

**Comment by ldgeo** [comment]
Indeed, thanks, it works. 
Not obvious this is a warning, i propose a small PR that.

**Comment by dmarteau** [comment]
> i propose a small PR for that.

Thx !
