### ISSUE TITLE
Usage in Kubernetes and Helm Charts

### ISSUE THREAD

**Issue by lucernae** [3liz/py-qgis-server#15]
Hi, I'm interested with this package to be used in Kubernetes via Helm Charts.
I have some questions:

- I saw the dockerhub repo https://hub.docker.com/r/3liz/qgis-map-server/tags , it doesn't seem to be any image for QGIS 3.14, yet. Is it not applicable or is it not tagged yet?
- Do you have any working example using Kubernetes manifests or maybe existing Helm charts?

**Comment by dmarteau** [comment]
>  or is it not tagged yet?
Not tagged yet, this is a matter of days.

> Do you have any working example using Kubernetes manifests or maybe existing Helm charts?

No, sorry.
