### ISSUE TITLE
Implements a setting environment or config to do not load layouts

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#16]
The `QgsProject::read` has a read flags parameter that can contain `QgsProject::ReadFlag::FlagDontLoadLayouts`. This flag improves projects read time but disable the QGIS Server GetPrint capabilities.

Like `QGIS_SERVER_DONT_LOAD_LAYOUTS` https://github.com/qgis/QGIS/pull/38240

**Comment by rldhont** [comment]
Suite à discussion la variable d'environnement va changer  de nom mais l'idée est la même.

**Comment by dmarteau** [comment]
Done in 4a0fbd8. 

See the [DISABLE_GETPRINT](https://py-qgis-server.readthedocs.io/en/latest/configuration.html#disable-getprint) configuration.
