### ISSUE TITLE
Implements a setting environment or config to force trust layer metadata

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#17]
In **QGIS 3.16**, a new `QgsProject::ReadFlag` has been added `QgsProject::ReadFlag::FlagTrustLayerMetadata`. This flag forced the QgsProject option : trust layer metadata.

Trust layer metadata is an option at the project level to improve project read time by using vector layer's extent defined in the project and disabling the check primary key unicity for Postgres/Postgis layers.

Do not use it if layers' extent is not fixed during the project's use.

**Comment by dmarteau** [comment]
Je dois attendre que la 3.16 soit releasé dans sa branche. Ces features sont encore dans la master.

**Comment by dmarteau** [comment]
> Do not use it if layers' extent is not fixed during the project's use.

This is actually a global configuration variable in the server settings used when loading project, il will be used the same way as from the config cache  in the default implementation.

**Comment by dmarteau** [comment]
Done in 4a0fbd8

**Comment by dmarteau** [comment]
See the [TRUST_LAYER_METADATA](https://py-qgis-server.readthedocs.io/en/latest/configuration.html#trust-layer-metadata) configuration.
