### ISSUE TITLE
Mettre le timeout avec Docker

### ISSUE THREAD

**Issue by TANK2003** [3liz/py-qgis-server#20]
Bonjour, est il possible de définir l'option timeout lorsqu'on l'utilise avec Docker ?

Merci d'avance

**Comment by dmarteau** [comment]
L'option timeout est disponible via la variable d'environnementf QGSRV_SERVER_TIMEOUT

**Comment by TANK2003** [comment]
Super, ca marche très bien ! merci encore pour ce boulot.
