### ISSUE TITLE
Project's data in subfolder

### ISSUE THREAD

**Issue by fisholo** [3liz/py-qgis-server#24]
Hi all and thanks for sharing tons of code!
I have this issue: no problem to server projects with data (gpkg) at the same level of project file, but when I create a subfolder with data inside no layers are rendered (nor in WMS or in WFS). 

Where am I wrong? 

Many thanks (in advance)

Fabrizio

**Comment by fisholo** [comment]
-- OK when --
project.qgs
test.gpkg

-- KO when --
project.qgs
|__vectors
     |__test.gpkg

**Comment by fisholo** [comment]
-- OK when --
project.qgs
test.gpkg

-- KO when --
project.qgs
|__vectors
     |__test.gpkg

**Comment by fisholo** [comment]
-- OK when --
project.qgs
test.gpkg

-- KO when --
project.qgs
|__vectors
____|__test.gpkg

**Comment by dmarteau** [comment]
The path of your layers in the `project.qgs` must reference the correct relative path of the data, 
i.e  he relative path of the data files must be the same as when you have created the project in Qgis desktop.

**Comment by rldhont** [comment]
Also Geopackages need to be an editable directory. OGR will create .wall and .shm files in the geopackage's directory.

**Comment by dmarteau** [comment]
Please read the note about geopackages: https://github.com/3liz/py-qgis-server/tree/master/docker#notes

**Comment by fisholo** [comment]
Many thanks to @rldhont and  @dmarteau!
It was an issue related to folder permissions! 
bye
