### ISSUE TITLE
Cross origin header pas present

### ISSUE THREAD

**Issue by TANK2003** [3liz/py-qgis-server#25]
Bonjour, 

j'ai un problème avec le CORS. en mettant la variable d'environnement `QGSRV_SERVER_CROSS_ORIGIN` à `yes`, j'ai toujours le même problème. Peut être je l'utilise pas comme il faut ?

Merci encore pour cet image docker, trés utile !

**Comment by dmarteau** [comment]
Bonjour et merci,

> J' ai un problème avec le CORS

Pouvez-vous décrire le problème plus précisemment.

Quelle version utilisez-vous ? Quel erreur vous retourne votre navigateur ?

Un discussion concernant CORS se trouve ici: https://github.com/3liz/py-qgis-server/issues/11, peut-être y trouverez vous des éléments de réponse.

**Comment by TANK2003** [comment]
Ahh super ca, je vais tester cet après midi et vous faire un retour asap !

**Comment by TANK2003** [comment]
Re, 

Le CORS marche super bien maintenant, merci pour la reponse rapide !
