### ISSUE TITLE
Provide either python packages or .deb

### ISSUE THREAD

**Issue by lhirlimann** [3liz/py-qgis-server#27]
Those would be nice to have when installing.

**Comment by dmarteau** [comment]
.deb is not relevant here....

**Comment by Gustry** [comment]
There seems to be everything for a python package in https://github.com/3liz/py-qgis-server/blob/master/setup.py
What is missing except the publication on pypi.org ?

This shoud work ?
```
pip install git+https://github.com/3liz/py-qgis-server.git
```

**Comment by Gustry** [comment]
Done https://pypi.org/project/py-qgis-server/

```bash
pip3 install py-qgis-server
```
