### ISSUE TITLE
Handle bad layers at QGIS project loading and throw exception

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#3]
https://github.com/qgis/QGIS/pull/9991

**Comment by dmarteau** [comment]
Bad layers are dismissed at QgsProject.read(...), so we end without the bad layers. it seems that there is no flags or status that enable to check if layer were dismissed, no exception is thrown.....

**Comment by dmarteau** [comment]
Fixed in 5e8ad90e6b5f043325285babf79657b4d501178f

Need to implement a QgsProjectBadLayerHandler to catch up invalid layers. This behavior can be activated/deactivated with the `cache.strict_check` (QGSRV_CACHE_STRICT_CHECK) option.

**Comment by dmarteau** [comment]
Note that the server will return a 422 HTTP error (Unprocessable entity) and not a 500.
