### ISSUE TITLE
I did not install 'build.manifest'.

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/py-qgis-server#31]
I'm trying to install py-qgis-server from 'pip install py-qgis-server'.
However, I get the error [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyqgisserver/build.manifest'.
Is this a mistake in the installation?
I did not install 'build.manifest'.

--------Err
root@i-16100000205417:/home/ubuntu# qgisserver
WARNING: Failed to read manifest ! [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyqgisserver/build.manifest'
Application path not initialized
WARNING: Failed to load 'PSutil', system metrics will not be collected
Traceback (most recent call last):
  File "/usr/local/bin/qgisserver", line 5, in <module>
    from pyqgisserver.server import main
  File "/usr/local/lib/python3.8/dist-packages/pyqgisserver/server.py", line 22, in <module>
    from .runtime import run_server
  File "/usr/local/lib/python3.8/dist-packages/pyqgisserver/runtime.py", line 36, in <module>
    from .qgspool import create_poolserver
  File "/usr/local/lib/python3.8/dist-packages/pyqgisserver/qgspool.py", line 33, in <module>
    from .qgsworker import QgsRequestHandler
  File "/usr/local/lib/python3.8/dist-packages/pyqgisserver/qgsworker.py", line 47, in <module>
    'PATCH': QgsServerRequest.PatchMethod,
AttributeError: type object 'QgsServerRequest' has no attribute 'PatchMethod'

**Comment by yamamoto-ryuzo** [comment]
"is build.manifest missing ? #12" is the same!

**Comment by dmarteau** [comment]
> I'm trying to install py-qgis-server from 'pip install py-qgis-server'.
However, I get the error [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyqgisserver/build.manifest'.

Does this occurs at `pip install` or when running the server ? FYI,  I have just installed py-qgis-server from `pip install ...` and had no errors.

**Comment by dmarteau** [comment]
Ok, the problem occurs is at runtime....

When building from Makefile the manifest is correctly added to the package but not in the package distributed from pypi. @Gustry can you check the packaging for pypi ?

**Comment by yamamoto-ryuzo** [comment]
I used the following method to install it.
--------------------
sudo su
#pipのインストール
apt update
apt -y install python3-pip
#
apt -y install python3-zmq
apt -y install python3-zmq-dbg

#py-qgis-serverのインストール
pip install py-qgis-server

**Comment by Gustry** [comment]
It's fixed in the next version released on PyPi.

I'm fine to make a new version, @dmarteau what do you think ?

**Comment by dmarteau** [comment]
This is is a warning and do not prevent running the server. This can wait the next version (coming soon)
