### ISSUE TITLE
Option to show decimal separator - QGIS_SERVER_SHOW_GROUP_SEPARATOR

### ISSUE THREAD

**Issue by u-cav** [3liz/py-qgis-server#33]
Do you know if/how we can enable the group separator in py-qgis-server, run with the docker image 3liz/qgis-map-server:3.16?
Our goal is to have the separator show up in the lizmap form popup.

I tried with the environment variable specified [here](https://docs.qgis.org/3.16/en/docs/server_manual/config.html#environment-variables):

`QGIS_SERVER_SHOW_GROUP_SEPARATOR: 'true'`

I also tried setting

`QGIS_OPTIONS_PATH: /srv/etc/qgis`

and setting the following in the configuration file:
```
[locale]
globalLocale=it_IT
overrideFlag=true
showGroupSeparator=true
userLocale=it_IT
```
But it doesn't seem to be working. I'm probably missing something obvious.

Thanks!

**Comment by dmarteau** [comment]
Qgis use the 'QgsServer' component under the hood, so any 'QGIS_SERVER_XXX' environment variable is valid as well 'QGIS_OPTIONS_PATH' (I use it without problem).

py-qgis-server does not interfere with these configuration variables, so I guess the problem may lies on the Lizmap side.

Hint: if you run py-qgis-server in debug mode `QGSRV_LOGGING_LEVEL: DEBUG`, `QGIS_OPTIONS_PATH: /src/test/qgis` and `QGIS_SERVER_SHOW_GROUP_SEPARATOR: 'true'`, you should see the folowing output:
```
qgis-server_1  | 2022-01-20 16:34:15,566	DEBUG	[33]	Qgis: Server: QGIS Server Settings: 
qgis-server_1  | 2022-01-20 16:34:15,566	DEBUG	[33]	Qgis: Server:   - QGIS_OPTIONS_PATH / '' (Override the default path for user configuration): '/src/tests/qgis' (read from ENVIRONMENT_VARIABLE)
...
qgis-server_1  | 2022-01-20 16:39:28,387	DEBUG	[33]	Qgis: Server:   - QGIS_SERVER_SHOW_GROUP_SEPARATOR / '/locale/showGroupSeparator' (Show group (thousands) separator): 'true' (read from ENVIRONMENT_VARIABLE)
```

These logs are issued by the `QgsServer` component itself` and show the actual server configuration.


Note that the Qgis server configuration ini file is expected to be located at `$QGIS_OPTIONS_PATH/QGIS/QGIS3.ini`.

**Comment by u-cav** [comment]
Thank you very much, this is very useful. I can confirm that the option is correctly loaded from the env and from the configuration file, so it must be something on the Lizmap side.

Sorry for the noise.
