### ISSUE TITLE
Use qgis-plugin-manager to install plugins

### ISSUE THREAD

**Issue by Gustry** [3liz/py-qgis-server#39]
According to the discussion : 
https://github.com/3liz/qgis-plugin-manager#installation

The readme is showing all command available in the CLI tool : `init`, `list`, `install` ...

According to the detected QGIS version, the latest plugin version will be installed.
Later, upgrading all plugins is convenient, like apt : 

```bash
qgis-plugin-manager update
qgis-plugin-manager upgrade
```

**Comment by dmarteau** [comment]
Fixed in 1d81e2106499a1c93a2180e74db90d73321d7d8f
