### ISSUE TITLE
config.ini not read for some values

### ISSUE THREAD

**Issue by billaj** [3liz/py-qgis-server#4]
Most config vars seem to have the following priority :
command-line(for some) > config.ini > env var > default
But it fails for some, including cache/rootdir, where it is :
command-line > env var > default
It should be command-line > config.ini > env var > default for all

details :
in server.py, line 67, we use get_config('cache')['rootdir'] as a default. But CONFIG is not loaded yet, so load_configuration is called by get_config, giving the env var or default value (btw, the header comments for load_configuration are outdated/misleading)
server.py, line 81 : we call read_config_file, overwriting CONFIG values with the ones from config.ini if provided
server.py, line 83/85 : read_config_dict with the env/default value read at line 67 (if there was no command-line argument), overwrites again CONFIG, effectively discarding the value read in the ini file at line 81

**Comment by dmarteau** [comment]
Fixed in b771fe6cec94bfa8b53b12cb0a94b993be0c41c1

**Comment by billaj** [comment]
Did not work when tested :
```
Traceback (most recent call last):
  File "/usr/local/bin/qgisserver", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pyqgisserver/server.py", line 113, in main
    args = read_configuration()
  File "/usr/local/lib/python3.5/dist-packages/pyqgisserver/server.py", line 75, in read_configuration
    read_config_file(config_file)
  File "/usr/local/lib/python3.5/dist-packages/pyqgisserver/config.py", line 96, in read_config_file
    CONFIG.read_file(cfgfile)
AttributeError: 'NoneType' object has no attribute 'read_file'
```
I think load_configuration() should be called before read_config_file() (also for config file>env var precedence)

**Comment by dmarteau** [comment]
Indeed: 12bc4562bdb90426b03c2318a655b350ad2a1d39

**Comment by billaj** [comment]
The fix works, thanks !
