### ISSUE TITLE
Is it necessary QGIS to use this server?

### ISSUE THREAD

**Issue by aguilarpablo** [3liz/py-qgis-server#46]
Hi, this is just a question. I don't quite understand if it is necessary to make requests to QGIS or with this functionality you can get what you need from postgis. Thanks for your approach!

**Comment by Gustry** [comment]
> with this functionality you can get what you need from postgis

Your question is not clear because you are mentioning "postgis".
This project is only related to "QGIS server" by having OGC services (WMS, WFS, OAPI etc) from your QGIS project. You can use any source of data working in QGIS desktop such as PostGIS layers.

> Is it necessary QGIS to use this server?

Yes

**Comment by dmarteau** [comment]
This is a server built around the Qgis server library and it requires that the QGis server framework  is installed in the running environment.

**Comment by aguilarpablo** [comment]
Ok, so I was wrong. I was looking for a way to develop a server that provides wfs or wms from where the data is, ie postgis, without going through geoserver or qgis. I close the issue, thanks!
