### ISSUE TITLE
Accept project stored in PostgreSQL Database

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#5]
In QGIS 3, it's possible to save the project to a PostgreSQL Database.

QGIS Server 3 is able to provide services based on a `MAP` with this type of encoded value `postgresql:?service=pg_geotuga&sslmode=disable&dbname=&schema=ortos&project=teste`

It could be interesting to have a way to defined a project stored in PostgreSQL Database.

for exemple, the PostgreSQL connexion for projects could be defined in a config file and the MAP parameter could be `pg://schema/project`

**Comment by dmarteau** [comment]
Actually, py-qgis-server supports the QGSRV_%s_PROTOCOL, where %s is replaced by whatever scheme used  in a MAP - This is used in production for implementing WPS results uri. May be that could be used for declaring `pg:` scheme.

What I need to know, if that is implemented at QgsProject level or at cache config lever. In the later
case, we have to  (re)implement how to fetching those projects because we do not use the default cache config.

**Comment by rldhont** [comment]
It is implemented at the `QgsProject` level. The `projectStorage` method [1](https://github.com/qgis/QGIS/blob/master/src/core/qgsproject.cpp#L618) used in `read` method [2](https://github.com/qgis/QGIS/blob/master/src/core/qgsproject.cpp#L1122) returns the `QgsProjectStorage` object associated to the `pg:` scheme in the `QgsProjectStorageRegistry` [3](https://github.com/qgis/QGIS/blob/master/src/core/qgsprojectstorageregistry.cpp#L31).

**Comment by dmarteau** [comment]
So, it is just  a matter for pyqsserver to acknowledge this protocol.

**Comment by rldhont** [comment]
it has been implemented, isn't it?

**Comment by dmarteau** [comment]
Yes, commit a643f352af9e7749a9a909eac60baff868b557f5

**Comment by lpofredc** [comment]
Could it be possible to have some more informations about using QGIS projects stored in postgres DB with QgisServer and lizmap? Thanks

**Comment by Gustry** [comment]
@lpofredc Better to create an issue I think.
And I don't think Lizmap config is supported, only QGIS Projects for now

**Comment by dmarteau** [comment]
@lpofredc This is not supported in Lizmap yet.
