### ISSUE TITLE
Improve how to use a symlink for a QGIS plugin

### ISSUE THREAD

**Issue by Gustry** [3liz/py-qgis-server#51]
It would be nice to have : 
* a better warning when the plugin is using a symlink
* indicate the workflow to use a QGIS plugin with the code located on the host (when we want to do some dev on a QGIS server plugin)

**Comment by dmarteau** [comment]
> indicate the workflow to use a QGIS plugin with the code located on the host (when we want to do some dev on a QGIS server plugin)

Yup, this a very common mistake with people using symlink with Docker container: they forget that the link target  must also exists inside the container.

**Comment by dmarteau** [comment]
> indicate the workflow to use a QGIS plugin with the code located on the host (when we want to do some dev on a QGIS 

Difficult to give a fit-them-all response since it depends heavily on how you are using the container. A the most basic level this resume to 'mount the target  path on the container' which is the only advice that the warning can spit out.
