### ISSUE TITLE
Add a QuickStart mode

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#55]
Add to the Readme the minimum docker command line to quickliy start py-qgis-server.

Something like `docker run -p 8080:8080 -v /path/to/qgis/projects:/projects 3liz/qgis-map-server`

**Comment by dmarteau** [comment]
Fixe with 794ca8a2c114557ec2eb0257eb04db94535fa2d3

Allow starting server as: `docker run -p 8080:8080 [--user <uid>[:<gid>]] -v /path/to/qgis/projects:/qgis-data`

**Comment by dmarteau** [comment]
The major feature is the support for the `--user` option.
