### ISSUE TITLE
Running proxy and workers separately with docker image show argument error

### ISSUE THREAD

**Issue by c-franz** [3liz/py-qgis-server#56]
Hi,

first, the py-qgis-server with docker-image works fine.
I have two more questions:

_How can i run the proxy and workers separately from docker image?_

When i will start the **workers**
`... qgisserver-worker --host=localhost --rootdir=/home/user1/projects`
it shows an error "unrecognized arguments"
`Running Xvfb
Running Qgis server worker
usage: qgisserver-worker [-h] [-d] [-c [PATH]] [--proxy-host host]
                         [--identity IDENTITY] [--rootdir PATH] [--version]
qgisserver-worker: error: unrecognized arguments: --host= --host=localhost`

_When i start proxy and workers on the same host (via docker images) which ports must i set for proxy and worker, because port 8080 is already used by one running docker image._

**Comment by dmarteau** [comment]
Workers are using ZMQ connect protocols to talk to the front-end proxy so there is no need to assign any ports on workers.

On the http front-end proxy you must also expose the ZMQ bind ports (default to 18080, 18090 and 18091).

The proxy-host is the host where your front-end is running.

Note that there is no advantage at all  to split wokers and front-end proxy if you are not in a cluster environment where your workers are running across multiple hosts.
