### ISSUE TITLE
Throw exception if bad layers are not restricted

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#6]
Handle bad layers at QGIS project loading and throw exception #3

Implement the same behavoir as fcgi QGIS Server https://github.com/qgis/QGIS/pull/33668

**Comment by dmarteau** [comment]
@rldhont for your information, this has nothing to do with the fcgi module: this is handled by the config cache module.

**Comment by rldhont** [comment]
The config cache module is used in the fcgi not in the py-qgis-server ;-)

**Comment by dmarteau** [comment]
This only a side effects.

**Comment by rldhont** [comment]
Here some test data 
[tests_data_qgis_server_load_project.zip](https://github.com/3liz/py-qgis-server/files/4045170/tests_data_qgis_server_load_project.zip)

**Comment by dmarteau** [comment]
Fixed in 1d026c1
