### ISSUE TITLE
How to force py-qgis-server to not use cache for GetCapabilities request ?

### ISSUE THREAD

**Issue by TANK2003** [3liz/py-qgis-server#60]
How to force py-qgis-server to not use cache for GetCapabilities request ? Or for all request if it is not possible

Thanks

**Comment by TANK2003** [comment]
Re,
### Description of the problem

- Yes i'am talking about the project Cache
- My stack : 
       - I have a plugin on top QGIS SERVER to handle layer permissions depending on the authorization token (in the  header of the request).
       - When  application boot a getcapabilities is called to list all layers which the user connected have rigths
- My problem : 
        - when user 1 perform the first getcapabilities request, py-qgi-server generate a cache; 
        - When user 2 perform another getcapabilities request after 2 mins, the cache of user 1 is return

So i'am tryng to regenerate getcapabilities request at each query

### Maybe a solution ? 

Maybe if i whrite a custom Loader schemes ? Where a projet will be the combination of `project name` &` user connected` ?

**Comment by dmarteau** [comment]
> Yes i'am talking about the project Cache

Your question is about the GetCapabilities response, which is not related to project's cache.

As a matter of fact the capabilities document is *not cached at all* by the server, but use standard client cache headers:

Py-qgis-server return getcapabilities response  with `Etag` headers, if the client request the same capabability document with a `If-None-Match` header with a matching Etag value then a `304 Not Modified`  is returned.

If you want the capabilities to be returned on each request,  then bypass client cache Etag headers (from javascript, use non-cached fetch requests) , then the request will reach your plugin.

You may also disable etag generation on server side by disabling  the [TRUST_LAYER_METADATA](https://docs.3liz.org/py-qgis-server/configuration.html#trust-layer-metadata) option.

**Comment by TANK2003** [comment]
Will try it known and give a feedback. Thanks !

**Comment by dmarteau** [comment]
* Check logs, eventually in debug mode, to check what's happening with requests.
* Check that your plugin is correctly initialized. You must find the following in logs 
```
est-py-qgis-server-qgis-server-1  | 2023-04-12 10:37:15,057	WARNING	[31]	Qgis: : SUCCESS - plugin foo  initialized
test-py-qgis-server-qgis-server-1  | 2023-04-12 10:37:15,057	INFO	[31]	Loaded plugin foo
...
```
* Use `curl` to  issue direct requests to py-qgis-server and check headers.

In debug mode, youu must have something like:
```
test-py-qgis-server-qgis-server-1  | 2023-04-12 10:39:14,890	DEBUG	[31]	Qgis: Server: REQUEST:GetCapabilities
test-py-qgis-server-qgis-server-1  | 2023-04-12 10:39:14,890	DEBUG	[31]	Qgis: Server: SERVICE:WFS
...
```
The above tell you that the request has reached Qgis server instance. If you get this and your plugin is loaded then your plugin must be called. Otherwise there is something wrong with your plugin.
