### ISSUE TITLE
Is there a problem in the refresh_cache method ?

### ISSUE THREAD

**Issue by TANK2003** [3liz/py-qgis-server#61]
In the refresh_cache method  https://github.com/3liz/py-qgis-server/blob/master/pyqgisserver/qgsworker.py#L299

```python 
def refresh_cache(cls) -> None:
        if cls._cache_check_interval <= 0 or time() - cls._cache_last_check < cls._cache_check_interval:
            return
        LOGGER.debug("Refreshing cache")
        iface = cls.qgis_server.serverInterface()
        for (key, state) in cls._cache_service.refresh():
            # Remove from Qgis server ConfigCache
            if state == UpdateState.UPDATED:
                details = cls._cache_service.peek(key)
                iface.removeConfigCacheEntry(details.project.fileName())

        cls._cache_last_check = time()
```

- If the check_interval congiguration value  ```  cls. _cache_check_interval  <= 0  ``` the cache will be never refresh ? 
- if time() - cls._cache_last_check < cls._cache_check_interval the cache will be never refresh ?

**Comment by dmarteau** [comment]
> If the check_interval congiguration value  cls. _cache_check_interval  <= 0 the cache will be never refresh ?

* If `check_interval congiguration value  cls. _cache_check_interval  <= 0` the cache will *not* refresh from this call  but will refresh when performing `cache lookup(...)`.  
 
* If `check_interval congiguration value  cls. _cache_check_interval  > 0` the cache will *potentially* refresh asynchronously from this code but will *not* refresh when performing `cache lookup(...)`.  

> if time() - cls._cache_last_check < cls._cache_check_interval the cache will be never refresh ?

* If `check_interval congiguration value  cls. _cache_check_interval  > 0` the cache will refresh asynchronously *only* when `time() - cls._cache_last_check >= cls._cache_check_interval the cache will be never refresh`.

The purpose of `CACHE_CHECK_INTERVAL` is to trigger refresh only at specified interval.

Of course, in all cases,  projects are reloaded only if they have been modified.

**Comment by TANK2003** [comment]
Thanks for all the details explanaition !

> What was your expectation ?

I thought that the variable CACHE_CHECK_INTERVAL represented the maximum time between the generation of the cache, but between two requests, not that it is even without  requests on server ; That is very good!

But I just did some tests, this condition is never true ` state == UpdateState.UPDATED` (https://github.com/3liz/py-qgis-server/blob/master/pyqgisserver/qgsworker.py#L306)   knowing that I use the default shceme (file)

**Comment by dmarteau** [comment]
> But I just did some tests, this condition is never true  state == UpdateState.UPDATED

It is true when  a modified version of the project has been reloaded on a cache refresh.

* UPDATED: the cache is UPDATED with a modified version of the project
* UNCHANGED: no change occured 
* INSERTED: new object have been added in CACHE
