### ISSUE TITLE
customize SVG search path?

### ISSUE THREAD

**Issue by luca76** [3liz/py-qgis-server#62]
We have custom SVG symbols. How can we add a mounted folder to SVG search path?

**Comment by dmarteau** [comment]
> How can we add a mounted folder to SVG search path ?

In what context ? Docker ?

**Comment by lucamanga** [comment]
Docker, but I solved it putting the svg into the projects folder.
Thank you!

**Comment by dmarteau** [comment]
Note: you can mount any folder as subfolder of mounted volumes
