### ISSUE TITLE
Qgis: WMS: Download of capabilities failed: SSL handshake failed

### ISSUE THREAD

**Issue by luca76** [3liz/py-qgis-server#64]
Hello, using 3liz qgis server docker.

Is there any way to tell to QGIS Server to ignore SSL errors?

In the log I'm having these lines:

```
2023-05-09 10:00:44,826 WARNING [50]    Qgis: WMS: Download of capabilities failed: SSL handshake failed
```

**Comment by dmarteau** [comment]
I don't think so but this a more a related Qgis issue than a py-qgis-server issue.

**Comment by luca76** [comment]
After some investigation, I think I solved the problem:

1) set this environment variable in docker-compose.yml:
```
QGIS_AUTH_DB_DIR_PATH: /srv/projects
```
2) copy an empty ```qgis-auth.db``` file from your QGIS profile (generated by the desktop app) in that docker volume

profit!

Reference: this issue https://github.com/opengisch/qgis-docker/commit/6766f88a7f7e27c850244791fa8d131cc6fa5ae2 states that without this setting, WMS/WFS/W*S over https do not work anymore

It would be useful to write this in the documentation
