### ISSUE TITLE
Workers update sequentially

### ISSUE THREAD

**Issue by lassitanskanen** [3liz/py-qgis-server#66]
Hi,

If apply updates to qgis project all workers will update it same time to LRU or static cache. Is it possible to update with delay between workers? In other words, rolling updates.

**Comment by dmarteau** [comment]
Actually no, each worker manage each own cache and update it.   

What would be the point/use  case to perform a rolling update ?

**Comment by lassitanskanen** [comment]
Large qgis projects that takes long to load to cache. Enchantment for updates handling.

**Comment by dmarteau** [comment]
> large qgis projects that takes long to load to cache

Interesting but, at first glance, not so easy  to implement since  workers manage cache independently from each other.

**Comment by lassitanskanen** [comment]
Could 0MQ push update requests to workers?

**Comment by dmarteau** [comment]
Yes, in theory that would be possible,  from the supervisor process that manage the worker pool,  this will implies some refactoring of the cache. 

The undesirable side effect that I see is that during the rolling the server may returns different responses depending on which worker is updated: if you do some map or vector tile requests or manage some  compositing with WMS requests, you may end with a complete mess with your final result.

**Comment by dmarteau** [comment]
Anyway, this would be a workaround to the  inherent fact tha Qgis server has a serious problem with project loading performances.  This a known issue and there is work in progress abount this issue.

At least, you may try `QGIS_SERVER_TRUST_LAYER_METADATA`, `QGIS_SERVER_FORCE_READONLY_LAYERS` and 
if you do not use `GetPrint` requests, disable loading composer data with `QGIS_SERVER_DISABLE_GETPRINT`: it may improve your loading time.
