### ISSUE TITLE
Capabilities to change port

### ISSUE THREAD

**Issue by lucadelu** [3liz/py-qgis-server#73]
It could be useful to have the capabilities to change the port of the server in Dockerfile, until now only 8080 seems to be possible to use. 

In the case you like the idea I could try to work on it

**Comment by lucadelu** [comment]
You are about exposing it, but you you want to run multiple qgis-server in the same network it could be useful to be sure to use different instances of the server using different port, since inside the containers speak with the original port and not the exposed one

**Comment by dmarteau** [comment]
>  but you you want to run multiple qgis-server in the same network  but you you want to run multiple qgis-server in the same network ...

Are you talking about docker network ?

If yes, you have to know that each container instance has its own DNS name, so there is no confict from the docker side, you only need to remap the *host* port of each instance.

If you scale a service with docker compose scale option or swarm , then you *cannot* map the port on the host side and your service name relsolve to multiple IP.

**Comment by dmarteau** [comment]
For a better understanding, can you provide a test case that illustrate the issue ? thanks.
