### ISSUE TITLE
QGIS Server implements QGIS_SERVER_IGNORE_BAD_LAYERS

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-server#9]
The variable `QGIS_SERVER_IGNORE_BAD_LAYERS` will be an equivalent to already `QGSRV_CACHE_STRICT_CHECK`.

The QGIS Pull Request https://github.com/qgis/QGIS/pull/35738

**Comment by dmarteau** [comment]
This option is used in server QgsConfigCache: py-qgis-server is using its own caching protocol so this config has no effects at all.
